// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActivityEventSource.
const (
	Gamified ActivityEventSource = "gamified"
	Organic  ActivityEventSource = "organic"
)

// Valid indicates whether the value is a known member of the ActivityEventSource enum.
func (e ActivityEventSource) Valid() bool {
	switch e {
	case Gamified:
		return true
	case Organic:
		return true
	default:
		return false
	}
}

// Defines values for ActivityResultRejectedReason.
const (
	ALREADYCOUNTED ActivityResultRejectedReason = "ALREADY_COUNTED"
	DAILYLIMIT     ActivityResultRejectedReason = "DAILY_LIMIT"
	DUPLICATE      ActivityResultRejectedReason = "DUPLICATE"
	DWELLTOOSHORT  ActivityResultRejectedReason = "DWELL_TOO_SHORT"
	NOMATCHINGTASK ActivityResultRejectedReason = "NO_MATCHING_TASK"
)

// Valid indicates whether the value is a known member of the ActivityResultRejectedReason enum.
func (e ActivityResultRejectedReason) Valid() bool {
	switch e {
	case ALREADYCOUNTED:
		return true
	case DAILYLIMIT:
		return true
	case DUPLICATE:
		return true
	case DWELLTOOSHORT:
		return true
	case NOMATCHINGTASK:
		return true
	default:
		return false
	}
}

// Defines values for ActivityType.
const (
	AdDeliveryEnabled     ActivityType = "ad.delivery_enabled"
	AdPhotoUpdated        ActivityType = "ad.photo_updated"
	AdPublished           ActivityType = "ad.published"
	AutotekaReportViewed  ActivityType = "autoteka.report_viewed"
	DealCompleted         ActivityType = "deal.completed"
	DeliverySectionOpened ActivityType = "delivery.section_opened"
	ListingCompared       ActivityType = "listing.compared"
	ListingFavorited      ActivityType = "listing.favorited"
	ListingViewed         ActivityType = "listing.viewed"
	ProfileUpdated        ActivityType = "profile.updated"
	ReviewLeft            ActivityType = "review.left"
	SearchSaved           ActivityType = "search.saved"
	SellerContacted       ActivityType = "seller.contacted"
)

// Valid indicates whether the value is a known member of the ActivityType enum.
func (e ActivityType) Valid() bool {
	switch e {
	case AdDeliveryEnabled:
		return true
	case AdPhotoUpdated:
		return true
	case AdPublished:
		return true
	case AutotekaReportViewed:
		return true
	case DealCompleted:
		return true
	case DeliverySectionOpened:
		return true
	case ListingCompared:
		return true
	case ListingFavorited:
		return true
	case ListingViewed:
		return true
	case ProfileUpdated:
		return true
	case ReviewLeft:
		return true
	case SearchSaved:
		return true
	case SellerContacted:
		return true
	default:
		return false
	}
}

// Defines values for CosmeticSourceType.
const (
	CosmeticSourceTypeLevel  CosmeticSourceType = "level"
	CosmeticSourceTypeReward CosmeticSourceType = "reward"
	CosmeticSourceTypeStreak CosmeticSourceType = "streak"
)

// Valid indicates whether the value is a known member of the CosmeticSourceType enum.
func (e CosmeticSourceType) Valid() bool {
	switch e {
	case CosmeticSourceTypeLevel:
		return true
	case CosmeticSourceTypeReward:
		return true
	case CosmeticSourceTypeStreak:
		return true
	default:
		return false
	}
}

// Defines values for CosmeticSlot.
const (
	Accessory  CosmeticSlot = "accessory"
	Background CosmeticSlot = "background"
	Frame      CosmeticSlot = "frame"
	Skin       CosmeticSlot = "skin"
)

// Valid indicates whether the value is a known member of the CosmeticSlot enum.
func (e CosmeticSlot) Valid() bool {
	switch e {
	case Accessory:
		return true
	case Background:
		return true
	case Frame:
		return true
	case Skin:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ACTIONLIMITREACHED   ErrorCode = "ACTION_LIMIT_REACHED"
	ACTIONRATELIMITED    ErrorCode = "ACTION_RATE_LIMITED"
	COSMETICNOTOWNED     ErrorCode = "COSMETIC_NOT_OWNED"
	EVENTREJECTED        ErrorCode = "EVENT_REJECTED"
	INTERNALERROR        ErrorCode = "INTERNAL_ERROR"
	NOTFOUND             ErrorCode = "NOT_FOUND"
	PETALREADYEXISTS     ErrorCode = "PET_ALREADY_EXISTS"
	PETISSLEEPING        ErrorCode = "PET_IS_SLEEPING"
	REWARDALREADYCLAIMED ErrorCode = "REWARD_ALREADY_CLAIMED"
	REWARDEXPIRED        ErrorCode = "REWARD_EXPIRED"
	REWARDNOTELIGIBLE    ErrorCode = "REWARD_NOT_ELIGIBLE"
	TOKENEXPIRED         ErrorCode = "TOKEN_EXPIRED"
	UNAUTHORIZED         ErrorCode = "UNAUTHORIZED"
	VALIDATIONERROR      ErrorCode = "VALIDATION_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ACTIONLIMITREACHED:
		return true
	case ACTIONRATELIMITED:
		return true
	case COSMETICNOTOWNED:
		return true
	case EVENTREJECTED:
		return true
	case INTERNALERROR:
		return true
	case NOTFOUND:
		return true
	case PETALREADYEXISTS:
		return true
	case PETISSLEEPING:
		return true
	case REWARDALREADYCLAIMED:
		return true
	case REWARDEXPIRED:
		return true
	case REWARDNOTELIGIBLE:
		return true
	case TOKENEXPIRED:
		return true
	case UNAUTHORIZED:
		return true
	case VALIDATIONERROR:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardPageScope.
const (
	LeaderboardPageScopeFriends LeaderboardPageScope = "friends"
	LeaderboardPageScopeLeague  LeaderboardPageScope = "league"
	LeaderboardPageScopeTop     LeaderboardPageScope = "top"
)

// Valid indicates whether the value is a known member of the LeaderboardPageScope enum.
func (e LeaderboardPageScope) Valid() bool {
	switch e {
	case LeaderboardPageScopeFriends:
		return true
	case LeaderboardPageScopeLeague:
		return true
	case LeaderboardPageScopeTop:
		return true
	default:
		return false
	}
}

// Defines values for MeSegment.
const (
	Both   MeSegment = "both"
	Buyer  MeSegment = "buyer"
	Seller MeSegment = "seller"
)

// Valid indicates whether the value is a known member of the MeSegment enum.
func (e MeSegment) Valid() bool {
	switch e {
	case Both:
		return true
	case Buyer:
		return true
	case Seller:
		return true
	default:
		return false
	}
}

// Defines values for MilestoneStatus.
const (
	MilestoneStatusCurrent MilestoneStatus = "current"
	MilestoneStatusLocked  MilestoneStatus = "locked"
	MilestoneStatusPassed  MilestoneStatus = "passed"
)

// Valid indicates whether the value is a known member of the MilestoneStatus enum.
func (e MilestoneStatus) Valid() bool {
	switch e {
	case MilestoneStatusCurrent:
		return true
	case MilestoneStatusLocked:
		return true
	case MilestoneStatusPassed:
		return true
	default:
		return false
	}
}

// Defines values for PetStage.
const (
	N1 PetStage = 1
	N2 PetStage = 2
	N3 PetStage = 3
	N4 PetStage = 4
)

// Valid indicates whether the value is a known member of the PetStage enum.
func (e PetStage) Valid() bool {
	switch e {
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	case N4:
		return true
	default:
		return false
	}
}

// Defines values for PetActionKind.
const (
	Feed  PetActionKind = "feed"
	Play  PetActionKind = "play"
	Sleep PetActionKind = "sleep"
	Wake  PetActionKind = "wake"
	Wash  PetActionKind = "wash"
)

// Valid indicates whether the value is a known member of the PetActionKind enum.
func (e PetActionKind) Valid() bool {
	switch e {
	case Feed:
		return true
	case Play:
		return true
	case Sleep:
		return true
	case Wake:
		return true
	case Wash:
		return true
	default:
		return false
	}
}

// Defines values for PetMood.
const (
	Happy    PetMood = "happy"
	Neutral  PetMood = "neutral"
	Radiant  PetMood = "radiant"
	Sad      PetMood = "sad"
	Sick     PetMood = "sick"
	Sleeping PetMood = "sleeping"
)

// Valid indicates whether the value is a known member of the PetMood enum.
func (e PetMood) Valid() bool {
	switch e {
	case Happy:
		return true
	case Neutral:
		return true
	case Radiant:
		return true
	case Sad:
		return true
	case Sick:
		return true
	case Sleeping:
		return true
	default:
		return false
	}
}

// Defines values for PresetId.
const (
	Blue   PresetId = "blue"
	Green  PresetId = "green"
	Purple PresetId = "purple"
)

// Valid indicates whether the value is a known member of the PresetId enum.
func (e PresetId) Valid() bool {
	switch e {
	case Blue:
		return true
	case Green:
		return true
	case Purple:
		return true
	default:
		return false
	}
}

// Defines values for Rarity.
const (
	Common    Rarity = "common"
	Legendary Rarity = "legendary"
	Rare      Rarity = "rare"
)

// Valid indicates whether the value is a known member of the Rarity enum.
func (e Rarity) Valid() bool {
	switch e {
	case Common:
		return true
	case Legendary:
		return true
	case Rare:
		return true
	default:
		return false
	}
}

// Defines values for RewardProgressUnit.
const (
	RewardProgressUnitDay   RewardProgressUnit = "day"
	RewardProgressUnitLevel RewardProgressUnit = "level"
	RewardProgressUnitTask  RewardProgressUnit = "task"
)

// Valid indicates whether the value is a known member of the RewardProgressUnit enum.
func (e RewardProgressUnit) Valid() bool {
	switch e {
	case RewardProgressUnitDay:
		return true
	case RewardProgressUnitLevel:
		return true
	case RewardProgressUnitTask:
		return true
	default:
		return false
	}
}

// Defines values for RewardStatus.
const (
	RewardStatusAvailable RewardStatus = "available"
	RewardStatusClaimed   RewardStatus = "claimed"
	RewardStatusExpired   RewardStatus = "expired"
	RewardStatusLocked    RewardStatus = "locked"
	RewardStatusUsed      RewardStatus = "used"
)

// Valid indicates whether the value is a known member of the RewardStatus enum.
func (e RewardStatus) Valid() bool {
	switch e {
	case RewardStatusAvailable:
		return true
	case RewardStatusClaimed:
		return true
	case RewardStatusExpired:
		return true
	case RewardStatusLocked:
		return true
	case RewardStatusUsed:
		return true
	default:
		return false
	}
}

// Defines values for RewardTier.
const (
	RewardTierCosmetic RewardTier = "cosmetic"
	RewardTierPremium  RewardTier = "premium"
	RewardTierSoft     RewardTier = "soft"
)

// Valid indicates whether the value is a known member of the RewardTier enum.
func (e RewardTier) Valid() bool {
	switch e {
	case RewardTierCosmetic:
		return true
	case RewardTierPremium:
		return true
	case RewardTierSoft:
		return true
	default:
		return false
	}
}

// Defines values for StatKey.
const (
	Clean  StatKey = "clean"
	Energy StatKey = "energy"
	Hunger StatKey = "hunger"
	Joy    StatKey = "joy"
)

// Valid indicates whether the value is a known member of the StatKey enum.
func (e StatKey) Valid() bool {
	switch e {
	case Clean:
		return true
	case Energy:
		return true
	case Hunger:
		return true
	case Joy:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusActive    TaskStatus = "active"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusExpired   TaskStatus = "expired"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusActive:
		return true
	case TaskStatusCompleted:
		return true
	case TaskStatusExpired:
		return true
	default:
		return false
	}
}

// Defines values for TaskClass.
const (
	Care    TaskClass = "care"
	Explore TaskClass = "explore"
	Setup   TaskClass = "setup"
	Weekly  TaskClass = "weekly"
)

// Valid indicates whether the value is a known member of the TaskClass enum.
func (e TaskClass) Valid() bool {
	switch e {
	case Care:
		return true
	case Explore:
		return true
	case Setup:
		return true
	case Weekly:
		return true
	default:
		return false
	}
}

// Defines values for GetLeaderboardParamsScope.
const (
	GetLeaderboardParamsScopeFriends GetLeaderboardParamsScope = "friends"
	GetLeaderboardParamsScopeLeague  GetLeaderboardParamsScope = "league"
	GetLeaderboardParamsScopeTop     GetLeaderboardParamsScope = "top"
)

// Valid indicates whether the value is a known member of the GetLeaderboardParamsScope enum.
func (e GetLeaderboardParamsScope) Valid() bool {
	switch e {
	case GetLeaderboardParamsScopeFriends:
		return true
	case GetLeaderboardParamsScopeLeague:
		return true
	case GetLeaderboardParamsScopeTop:
		return true
	default:
		return false
	}
}

// ActionResult defines model for ActionResult.
type ActionResult struct {
	CareXpCapReached *bool `json:"careXpCapReached,omitempty"`

	// CareXpToday Сколько XP ухода начислено за сутки
	CareXpToday *int `json:"careXpToday,omitempty"`
	LeveledUp   bool `json:"leveledUp"`
	Pet         Pet  `json:"pet"`

	// StatCapped Показатель был 100 ДО действия. XP не начислен, анимацию всё равно играем
	StatCapped        bool      `json:"statCapped"`
	UnlockedRewardIds *[]string `json:"unlockedRewardIds,omitempty"`

	// XpGained Уже с множителями и округлением вниз
	XpGained int `json:"xpGained"`
}

// ActionState defines model for ActionState.
type ActionState struct {
	CooldownUntil *time.Time `json:"cooldownUntil,omitempty"`

	// Remaining Сколько раз ещё можно сегодня
	Remaining int `json:"remaining"`

	// XpCapped Суточный потолок ухода исчерпан
	XpCapped bool `json:"xpCapped"`
}

// ActivityEvent defines model for ActivityEvent.
type ActivityEvent struct {
	// EventId Для дедупликации
	EventId    openapi_types.UUID `json:"eventId"`
	OccurredAt time.Time          `json:"occurredAt"`
	Payload    *struct {
		AdId       *string `json:"adId,omitempty"`
		CategoryId *string `json:"categoryId,omitempty"`

		// DwellMs Для listing.viewed зачёт от 8000
		DwellMs    *int      `json:"dwellMs,omitempty"`
		Fields     *[]string `json:"fields,omitempty"`
		ListingId  *string   `json:"listingId,omitempty"`
		ListingIds *[]string `json:"listingIds,omitempty"`
		QueryHash  *string   `json:"queryHash,omitempty"`
	} `json:"payload,omitempty"`

	// Source gamified означает «вызвано задачей». Бэк обязан пробросить флаг в аналитику: такие события исключаются из статистики продавца и из ранжирования
	Source ActivityEventSource `json:"source"`

	// Type Первые девять могут быть задачами. Последние четыре — только признания: дают XP, но никогда не выдаются как задача, иначе продавцы получат спам
	Type ActivityType `json:"type"`
}

// ActivityEventSource gamified означает «вызвано задачей». Бэк обязан пробросить флаг в аналитику: такие события исключаются из статистики продавца и из ранжирования
type ActivityEventSource string

// ActivityResult defines model for ActivityResult.
type ActivityResult struct {
	Accepted  *[]openapi_types.UUID `json:"accepted,omitempty"`
	LeveledUp *bool                 `json:"leveledUp,omitempty"`
	Pet       *Pet                  `json:"pet,omitempty"`
	Rejected  *[]struct {
		EventId *string                       `json:"eventId,omitempty"`
		Reason  *ActivityResultRejectedReason `json:"reason,omitempty"`
	} `json:"rejected,omitempty"`
	Tasks             *[]Task   `json:"tasks,omitempty"`
	UnlockedRewardIds *[]string `json:"unlockedRewardIds,omitempty"`
	XpGained          *int      `json:"xpGained,omitempty"`
}

// ActivityResultRejectedReason defines model for ActivityResult.Rejected.Reason.
type ActivityResultRejectedReason string

// ActivityType Первые девять могут быть задачами. Последние четыре — только признания: дают XP, но никогда не выдаются как задача, иначе продавцы получат спам
type ActivityType string

// AuthResult defines model for AuthResult.
type AuthResult struct {
	AccessToken string `json:"accessToken"`

	// ExpiresIn Examples: 900
	ExpiresIn    *int   `json:"expiresIn,omitempty"`
	RefreshToken string `json:"refreshToken"`
	User         *Me    `json:"user,omitempty"`
}

// Config defines model for Config.
type Config struct {
	Actions *map[string]struct {
		DailyLimit *int     `json:"dailyLimit,omitempty"`
		Effect     *int     `json:"effect,omitempty"`
		Label      *string  `json:"label,omitempty"`
		Stat       *StatKey `json:"stat,omitempty"`
		Xp         *int     `json:"xp,omitempty"`
	} `json:"actions,omitempty"`

	// DailyCareXpCap Examples: 40
	DailyCareXpCap *int `json:"dailyCareXpCap,omitempty"`
	LevelCurve     *struct {
		// Base Examples: 100
		Base *int `json:"base,omitempty"`

		// Factor Examples: 1.25
		Factor *float32 `json:"factor,omitempty"`

		// MaxLevel Examples: 25
		MaxLevel *int `json:"maxLevel,omitempty"`

		// RoundTo Examples: 10
		RoundTo *int `json:"roundTo,omitempty"`
	} `json:"levelCurve,omitempty"`
	Milestones *[]Milestone `json:"milestones,omitempty"`
	Moods      *[]struct {
		// Id Производная от МИНИМАЛЬНОГО показателя. Клиент её не вычисляет
		Id         *PetMood `json:"id,omitempty"`
		Label      *string  `json:"label,omitempty"`
		MinStat    *int     `json:"minStat,omitempty"`
		Multiplier *float32 `json:"multiplier,omitempty"`
	} `json:"moods,omitempty"`
	Stats *map[string]struct {
		Color        *string  `json:"color,omitempty"`
		DecayPerHour *float32 `json:"decayPerHour,omitempty"`
		Label        *string  `json:"label,omitempty"`
	} `json:"stats,omitempty"`
	StreakTiers *[]struct {
		From       *int     `json:"from,omitempty"`
		Multiplier *float32 `json:"multiplier,omitempty"`
	} `json:"streakTiers,omitempty"`
}

// Cosmetic defines model for Cosmetic.
type Cosmetic struct {
	// AssetKey Ключ, по которому фронт рисует SVG. Бэк картинок не хранит
	//
	// Examples: scarf_explorer
	AssetKey string `json:"assetKey"`
	Equipped bool   `json:"equipped"`
	Id       string `json:"id"`

	// LockedHint Examples: Откроется на 10 уровне
	LockedHint *string `json:"lockedHint,omitempty"`

	// Name Examples: Шарф исследователя
	Name       string       `json:"name"`
	ObtainedAt *time.Time   `json:"obtainedAt,omitempty"`
	Owned      bool         `json:"owned"`
	Rarity     Rarity       `json:"rarity"`
	Slot       CosmeticSlot `json:"slot"`
	Source     *struct {
		// Label Examples: Веха 7 дней
		Label *string             `json:"label,omitempty"`
		Type  *CosmeticSourceType `json:"type,omitempty"`
	} `json:"source,omitempty"`
}

// CosmeticSourceType defines model for Cosmetic.Source.Type.
type CosmeticSourceType string

// CosmeticSlot defines model for CosmeticSlot.
type CosmeticSlot string

// DailySummary defines model for DailySummary.
type DailySummary struct {
	// AiNote Персональная фраза от питомца. Генерируется на бэке: ключи LLM не должны попасть в браузер
	AiNote    *string `json:"aiNote,omitempty"`
	Breakdown *[]struct {
		Count *int    `json:"count,omitempty"`
		Key   *string `json:"key,omitempty"`
		Label *string `json:"label,omitempty"`
		Xp    *int    `json:"xp,omitempty"`
	} `json:"breakdown,omitempty"`
	Date       *openapi_types.Date `json:"date,omitempty"`
	Multiplier *float32            `json:"multiplier,omitempty"`
	Pet        *struct {
		LevelAfter  *int `json:"levelAfter,omitempty"`
		LevelBefore *int `json:"levelBefore,omitempty"`

		// MoodAfter Производная от МИНИМАЛЬНОГО показателя. Клиент её не вычисляет
		MoodAfter *PetMood `json:"moodAfter,omitempty"`

		// MoodBefore Производная от МИНИМАЛЬНОГО показателя. Клиент её не вычисляет
		MoodBefore *PetMood `json:"moodBefore,omitempty"`

		// StatsAfter Целые 0..100. Потолок жёсткий: 82 + 30 = 100, остаток сгорает
		StatsAfter *Stats `json:"statsAfter,omitempty"`
	} `json:"pet,omitempty"`

	// ShouldShow Решает сервер, не клиент
	ShouldShow *bool   `json:"shouldShow,omitempty"`
	Streak     *Streak `json:"streak,omitempty"`
	Tomorrow   *struct {
		MultiplierWillBe *float32 `json:"multiplierWillBe,omitempty"`
		NextReward       *Reward  `json:"nextReward,omitempty"`
		StreakWillBe     *int     `json:"streakWillBe,omitempty"`
		Tasks            *[]Task  `json:"tasks,omitempty"`
	} `json:"tomorrow,omitempty"`
	XpTotal *int `json:"xpTotal,omitempty"`
}

// Envelope defines model for Envelope.
type Envelope struct {
	// Data Полезная нагрузка. null при ошибке
	Data interface{} `json:"data,omitempty"`
	Meta Meta        `json:"meta"`
}

// ErrorCode Машинный код. Фронт ветвится ТОЛЬКО по нему: message перепишут при вычитке текстов, и клиент молча сломается.
type ErrorCode string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Data any  `json:"data,omitempty"`
	Meta Meta `json:"meta"`
}

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry struct {
	IsMe     *bool     `json:"isMe,omitempty"`
	Level    *int      `json:"level,omitempty"`
	Nickname *string   `json:"nickname,omitempty"`
	PresetId *PresetId `json:"presetId,omitempty"`
	Rank     *int      `json:"rank,omitempty"`
	Streak   *int      `json:"streak,omitempty"`
	UserId   *string   `json:"userId,omitempty"`
	WeeklyXp *int      `json:"weeklyXp,omitempty"`
}

// LeaderboardPage defines model for LeaderboardPage.
type LeaderboardPage struct {
	Items  *[]LeaderboardEntry `json:"items,omitempty"`
	League *struct {
		EndsAt        *time.Time `json:"endsAt,omitempty"`
		Id            *string    `json:"id,omitempty"`
		Name          *string    `json:"name,omitempty"`
		PromoteCount  *int       `json:"promoteCount,omitempty"`
		RelegateCount *int       `json:"relegateCount,omitempty"`
	} `json:"league,omitempty"`
	Me         *LeaderboardEntry     `json:"me,omitempty"`
	NextCursor *string               `json:"nextCursor,omitempty"`
	Scope      *LeaderboardPageScope `json:"scope,omitempty"`
}

// LeaderboardPageScope defines model for LeaderboardPage.Scope.
type LeaderboardPageScope string

// Me defines model for Me.
type Me struct {
	AvatarUrl *string    `json:"avatarUrl,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        string     `json:"id"`
	Nickname  string     `json:"nickname"`

	// OnboardingCompleted Флаг на сервере, а не в localStorage: иначе онбординг повторится на другом устройстве
	OnboardingCompleted bool `json:"onboardingCompleted"`

	// Segment Определяет выдачу задач. Задачи продавца бессмысленны без активных объявлений
	Segment MeSegment `json:"segment"`

	// Timezone Examples: Europe/Moscow
	Timezone string `json:"timezone"`
}

// MeSegment Определяет выдачу задач. Задачи продавца бессмысленны без активных объявлений
type MeSegment string

// Meta defines model for Meta.
type Meta struct {
	// Code ВСЕГДА число, дублирует HTTP-статус
	//
	// Examples: 200
	Code int `json:"code"`

	// Error Машинный код. Фронт ветвится ТОЛЬКО по нему: message перепишут при вычитке текстов, и клиент молча сломается.
	Error *ErrorCode `json:"error,omitempty"`

	// Message Текст для пользователя, на русском
	Message string `json:"message"`

	// RequestId Эхо заголовка X-Request-Id. По нему бэк находит лог по скриншоту бага
	RequestId *openapi_types.UUID `json:"requestId,omitempty"`

	// RetryAfterSec Только при 429
	RetryAfterSec *int `json:"retryAfterSec,omitempty"`
}

// Milestone defines model for Milestone.
type Milestone struct {
	// Days Examples: 100
	Days     *int             `json:"days,omitempty"`
	RewardId *string          `json:"rewardId,omitempty"`
	Status   *MilestoneStatus `json:"status,omitempty"`

	// Title Examples: Сотня
	Title *string `json:"title,omitempty"`
}

// MilestoneStatus defines model for Milestone.Status.
type MilestoneStatus string

// Pet defines model for Pet.
type Pet struct {
	Actions map[string]ActionState `json:"actions"`

	// Equipped id надетой косметики
	Equipped *[]string `json:"equipped,omitempty"`
	Id       string    `json:"id"`
	Level    int       `json:"level"`

	// Mood Производная от МИНИМАЛЬНОГО показателя. Клиент её не вычисляет
	Mood PetMood `json:"mood"`

	// MoodMultiplier Examples: 1
	MoodMultiplier float32 `json:"moodMultiplier"`
	Name           string  `json:"name"`
	NextStage      *struct {
		AtLevel *int    `json:"atLevel,omitempty"`
		Label   *string `json:"label,omitempty"`
		Stage   *int    `json:"stage,omitempty"`
	} `json:"nextStage,omitempty"`
	PresetId   PresetId   `json:"presetId"`
	SleepUntil *time.Time `json:"sleepUntil,omitempty"`
	Stage      PetStage   `json:"stage"`

	// StageLabel Examples: Искатель
	StageLabel *string `json:"stageLabel,omitempty"`

	// Stats Целые 0..100. Потолок жёсткий: 82 + 30 = 100, остаток сгорает
	Stats Stats `json:"stats"`

	// StreakMultiplier Examples: 1.2
	StreakMultiplier *float32 `json:"streakMultiplier,omitempty"`
	TotalXp          int      `json:"totalXp"`

	// UpdatedAt Момент, на который посчитан decay. Точка отсчёта для следующего пересчёта
	UpdatedAt time.Time `json:"updatedAt"`

	// Xp XP внутри текущего уровня
	Xp int `json:"xp"`

	// XpToNext round10(100 * 1.25^(level-1))
	XpToNext int `json:"xpToNext"`
}

// PetStage defines model for Pet.Stage.
type PetStage int

// PetActionKind defines model for PetActionKind.
type PetActionKind string

// PetMood Производная от МИНИМАЛЬНОГО показателя. Клиент её не вычисляет
type PetMood string

// PetPreset defines model for PetPreset.
type PetPreset struct {
	// Colors Четыре цвета логотипа Авито в ролях: тело, большое ухо, малое ухо, лапа
	Colors *struct {
		Body *string `json:"body,omitempty"`
		EarL *string `json:"earL,omitempty"`
		EarS *string `json:"earS,omitempty"`
		Paw  *string `json:"paw,omitempty"`
	} `json:"colors,omitempty"`
	Id *PresetId `json:"id,omitempty"`

	// Name Examples: Ави
	Name *string `json:"name,omitempty"`

	// Trait Examples: спокойный
	Trait *string `json:"trait,omitempty"`
}

// PresetId defines model for PresetId.
type PresetId string

// Profile defines model for Profile.
type Profile struct {
	// Activity Хитмап за 30 дней
	Activity *[]struct {
		Date  *openapi_types.Date `json:"date,omitempty"`
		Value *int                `json:"value,omitempty"`
	} `json:"activity,omitempty"`
	Pet   *Pet `json:"pet,omitempty"`
	Stats *struct {
		AvgXpPerDay    *int `json:"avgXpPerDay,omitempty"`
		CareActions    *int `json:"careActions,omitempty"`
		DaysInGame     *int `json:"daysInGame,omitempty"`
		RewardsClaimed *int `json:"rewardsClaimed,omitempty"`
		TasksCompleted *int `json:"tasksCompleted,omitempty"`
	} `json:"stats,omitempty"`
	Streak *Streak `json:"streak,omitempty"`
	User   *Me     `json:"user,omitempty"`
}

// Rarity defines model for Rarity.
type Rarity string

// Reward defines model for Reward.
type Reward struct {
	ClaimedAt *time.Time `json:"claimedAt,omitempty"`

	// ConditionLabel ГОТОВЫЙ текст с сервера. Фронт не склеивает фразы из чисел
	//
	// Examples: Достигни 10 уровня
	ConditionLabel string `json:"conditionLabel"`

	// CosmeticId Если tier=cosmetic
	CosmeticId  *string `json:"cosmeticId,omitempty"`
	Description *string `json:"description,omitempty"`

	// EtaDays Оценка сервера по темпу пользователя
	EtaDays   *int       `json:"etaDays,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Id        string     `json:"id"`
	Progress  struct {
		Current int                `json:"current"`
		Target  int                `json:"target"`
		Unit    RewardProgressUnit `json:"unit"`
	} `json:"progress"`

	// PromoCode ТОЛЬКО при status claimed или used. В остальных случаях поле отсутствует
	//
	// Examples: AVI-7K3M-92XQ
	PromoCode *string      `json:"promoCode,omitempty"`
	RedeemUrl *string      `json:"redeemUrl,omitempty"`
	Status    RewardStatus `json:"status"`

	// Tier cosmetic — себестоимость 0 · soft — бонусы кошелька, мелкие скидки · premium — платные услуги Авито, только с 10 уровня и вехи 100
	Tier RewardTier `json:"tier"`

	// Title Examples: Скидка 20% на Авито Доставку
	Title string `json:"title"`
}

// RewardProgressUnit defines model for Reward.Progress.Unit.
type RewardProgressUnit string

// RewardStatus defines model for RewardStatus.
type RewardStatus string

// RewardTier cosmetic — себестоимость 0 · soft — бонусы кошелька, мелкие скидки · premium — платные услуги Авито, только с 10 уровня и вехи 100
type RewardTier string

// StatKey defines model for StatKey.
type StatKey string

// Stats Целые 0..100. Потолок жёсткий: 82 + 30 = 100, остаток сгорает
type Stats struct {
	Clean  int `json:"clean"`
	Energy int `json:"energy"`
	Hunger int `json:"hunger"`
	Joy    int `json:"joy"`
}

// Streak defines model for Streak.
type Streak struct {
	// Best Никогда не уменьшается
	Best    int   `json:"best"`
	Broken  *bool `json:"broken,omitempty"`
	Current int   `json:"current"`
	Freezes int   `json:"freezes"`

	// FrozenUsed Заморозка списана автоматически — сказать честно в сводке
	FrozenUsed *bool `json:"frozenUsed,omitempty"`

	// Multiplier 1–6 дн ×1.0 · 7–13 ×1.1 · 14–29 ×1.2 · 30–99 ×1.3 · 100–499 ×1.4 · 500+ ×1.5
	//
	// Examples: 1.2
	Multiplier    float32 `json:"multiplier"`
	NextMilestone *struct {
		Days     *int    `json:"days,omitempty"`
		DaysLeft *int    `json:"daysLeft,omitempty"`
		RewardId *string `json:"rewardId,omitempty"`
		Title    *string `json:"title,omitempty"`
	} `json:"nextMilestone,omitempty"`
	TodayCounted bool `json:"todayCounted"`
}

// Task defines model for Task.
type Task struct {
	// Class care — внутри игры; setup — нулевой след у других людей (сохранить поиск, обновить фото своего объявления); explore — слабый след (просмотры, сравнение, избранное); weekly — недельная
	Class     TaskClass `json:"class"`
	DeepLink  *string   `json:"deepLink,omitempty"`
	ExpiresAt time.Time `json:"expiresAt"`

	// Icon Ключ иконки, фронт рисует SVG сам
	Icon     string `json:"icon"`
	Id       string `json:"id"`
	Progress struct {
		Current int `json:"current"`
		Target  int `json:"target"`
	} `json:"progress"`
	RequiresEvent *[]ActivityType `json:"requiresEvent,omitempty"`
	Status        TaskStatus      `json:"status"`

	// Subtitle Examples: в разделе «Электроника»
	Subtitle *string `json:"subtitle,omitempty"`

	// Title Examples: Посмотри 3 объявления
	Title    string `json:"title"`
	XpReward int    `json:"xpReward"`
}

// TaskStatus defines model for Task.Status.
type TaskStatus string

// TaskClass care — внутри игры; setup — нулевой след у других людей (сохранить поиск, обновить фото своего объявления); explore — слабый след (просмотры, сравнение, избранное); weekly — недельная
type TaskClass string

// TasksToday defines model for TasksToday.
type TasksToday struct {
	Items *[]Task `json:"items,omitempty"`

	// ResetsAt 04:00 по timezone аккаунта
	ResetsAt *time.Time `json:"resetsAt,omitempty"`
}

// Tokens defines model for Tokens.
type Tokens struct {
	AccessToken string `json:"accessToken"`

	// ExpiresIn Examples: 900
	ExpiresIn    *int   `json:"expiresIn,omitempty"`
	RefreshToken string `json:"refreshToken"`
}

// CosmeticId defines model for CosmeticId.
type CosmeticId = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// IdempotencyKeyRequired defines model for IdempotencyKeyRequired.
type IdempotencyKeyRequired = openapi_types.UUID

// RewardId defines model for RewardId.
type RewardId = string

// TaskId defines model for TaskId.
type TaskId = string

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// PetOk defines model for PetOk.
type PetOk struct {
	Data *Pet `json:"data,omitempty"`
	Meta Meta `json:"meta"`
}

// RateLimited defines model for RateLimited.
type RateLimited = ErrorEnvelope

// RewardOk defines model for RewardOk.
type RewardOk struct {
	Data *Reward `json:"data,omitempty"`
	Meta Meta    `json:"meta"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// ValidationError defines model for ValidationError.
type ValidationError = ErrorEnvelope

// PostActivityEventsJSONBody defines parameters for PostActivityEvents.
type PostActivityEventsJSONBody struct {
	Events []ActivityEvent `json:"events"`
}

// PostActivityEventsParams defines parameters for PostActivityEvents.
type PostActivityEventsParams struct {
	// IdempotencyKey UUID с клиента. Повтор с тем же ключом возвращает прежний результат, а не ошибку.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// PostAuthRefreshJSONBody defines parameters for PostAuthRefresh.
type PostAuthRefreshJSONBody struct {
	RefreshToken string `json:"refreshToken"`
}

// PostAuthRegisterJSONBody defines parameters for PostAuthRegister.
type PostAuthRegisterJSONBody struct {
	// Login Логин для входа (решение команды 06.08)
	Login string `json:"login"`

	// Nickname Отображаемое имя, необязательно: по умолчанию берётся из login. Не учётные данные — см. Me.nickname
	Nickname *string `json:"nickname,omitempty"`

	// Password Хранится только хешем; в ответах не возвращается
	Password string `json:"password"`

	// Timezone Examples: Europe/Moscow
	Timezone string `json:"timezone"`
}

// PostDemoAdvanceDayJSONBody defines parameters for PostDemoAdvanceDay.
type PostDemoAdvanceDayJSONBody struct {
	Days *int `json:"days,omitempty"`
}

// GetLeaderboardParams defines parameters for GetLeaderboard.
type GetLeaderboardParams struct {
	Scope  GetLeaderboardParamsScope `form:"scope" json:"scope"`
	Cursor *string                   `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int                      `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetLeaderboardParamsScope defines parameters for GetLeaderboard.
type GetLeaderboardParamsScope string

// PostPetActionsJSONBody defines parameters for PostPetActions.
type PostPetActionsJSONBody struct {
	// ActionId UUID с клиента. Защищает от двойного тапа: повтор возвращает прежний результат.
	ActionId openapi_types.UUID `json:"actionId"`
	Kind     PetActionKind      `json:"kind"`
}

// PostPetActionsParams defines parameters for PostPetActions.
type PostPetActionsParams struct {
	// IdempotencyKey UUID с клиента. Повтор с тем же ключом возвращает прежний результат, а не ошибку.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostPetsJSONBody defines parameters for PostPets.
type PostPetsJSONBody struct {
	Name     *string  `json:"name,omitempty"`
	PresetId PresetId `json:"presetId"`
}

// PostPetsParams defines parameters for PostPets.
type PostPetsParams struct {
	// IdempotencyKey UUID с клиента. Повтор с тем же ключом возвращает прежний результат, а не ошибку.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetRewardsParams defines parameters for GetRewards.
type GetRewardsParams struct {
	Status *RewardStatus `form:"status,omitempty" json:"status,omitempty"`
}

// PostRewardsRewardIdClaimParams defines parameters for PostRewardsRewardIdClaim.
type PostRewardsRewardIdClaimParams struct {
	// IdempotencyKey Обязателен: ретрай при плохой сети не должен выдать второй промокод.
	IdempotencyKey IdempotencyKeyRequired `json:"Idempotency-Key"`
}

// GetSummaryDailyParams defines parameters for GetSummaryDaily.
type GetSummaryDailyParams struct {
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// PostSummaryDailySeenJSONBody defines parameters for PostSummaryDailySeen.
type PostSummaryDailySeenJSONBody struct {
	Date openapi_types.Date `json:"date"`
}

// PostActivityEventsJSONRequestBody defines body for PostActivityEvents for application/json ContentType.
type PostActivityEventsJSONRequestBody PostActivityEventsJSONBody

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody PostAuthRefreshJSONBody

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody PostAuthRegisterJSONBody

// PostDemoAdvanceDayJSONRequestBody defines body for PostDemoAdvanceDay for application/json ContentType.
type PostDemoAdvanceDayJSONRequestBody PostDemoAdvanceDayJSONBody

// PostPetActionsJSONRequestBody defines body for PostPetActions for application/json ContentType.
type PostPetActionsJSONRequestBody PostPetActionsJSONBody

// PostPetsJSONRequestBody defines body for PostPets for application/json ContentType.
type PostPetsJSONRequestBody PostPetsJSONBody

// PostSummaryDailySeenJSONRequestBody defines body for PostSummaryDailySeen for application/json ContentType.
type PostSummaryDailySeenJSONRequestBody PostSummaryDailySeenJSONBody
