/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname: string;
                        /** @example Europe/Moscow */
                        timezone: string;
                    };
                };
            };
            responses: {
                /** @description Токены и профиль */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["AuthResult"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname: string;
                    };
                };
            };
            responses: {
                /** @description Токены и профиль */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["AuthResult"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить access-токен */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Новая пара токенов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Tokens"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Профиль */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Me"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Справочник экономики
         * @description Фронт берёт отсюда скорость падения показателей, эффекты действий, пороги настроений, кривую уровней и множители стрика. Хардкодить эти числа в клиенте запрещено: при смене баланса разъедется. Кэшируется на сутки, поддерживает ETag.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Константы экономики */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Config"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Три расцветки для онбординга */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список пресетов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["PetPreset"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать питомца */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description UUID с клиента. Повтор с тем же ключом возвращает прежний результат, а не ошибку. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        presetId: components["schemas"]["PresetId"];
                        name?: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["PetOk"];
                /** @description Питомец уже создан */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Состояние питомца
         * @description Сервер лениво досчитывает decay от pet.updatedAt до now и, если это первый вход за сутки, начисляет XP за вход. Крон для показателей не нужен.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["PetOk"];
                401: components["responses"]["Unauthorized"];
                /** @description Питомца ещё нет — вести на онбординг */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pet/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Действие ухода
         * @description Единственный способ поднять показатель. Возвращает ПОЛНОЕ состояние питомца, чтобы фронт не собирал его по кускам и не ловил гонки.
         *
         *     statCapped=true означает: показатель уже был 100 ДО действия, XP не начислен. Фронт всё равно проигрывает анимацию — эмоция бесплатная.
         *
         *     careXpCapReached=true означает: суточный потолок ухода исчерпан. Кнопки остаются активными, меняется только подпись.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description UUID с клиента. Повтор с тем же ключом возвращает прежний результат, а не ошибку. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        kind: components["schemas"]["PetActionKind"];
                        /**
                         * Format: uuid
                         * @description UUID с клиента. Защищает от двойного тапа: повтор возвращает прежний результат.
                         */
                        actionId: string;
                    };
                };
            };
            responses: {
                /** @description Питомец обновлён */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ActionResult"];
                        };
                    };
                };
                /** @description ACTION_LIMIT_REACHED или PET_IS_SLEEPING */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Задачи дня
         * @description Три задачи: одна care, одна setup, одна explore. Ротация в 04:00 по timezone аккаунта. Выдача зависит от segment: задачи продавца не показываем тем, у кого нет активных объявлений.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список задач */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["TasksToday"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Зафиксировать переход в Авито
         * @description Не меняет прогресс. Только логирует намерение и отдаёт deepLink.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ссылка */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: {
                                /** Format: uri */
                                deepLink?: string;
                            };
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * События активности — единственный способ двигать прогресс задач
         * @description Эндпоинта «выполнить задачу» НЕ СУЩЕСТВУЕТ. Клиент сообщает факты, сервер сам решает, что они засчитывают.
         *
         *     УСЛОВИЯ ЗАЧЁТА:
         *     · listing.viewed — dwellMs >= 8000 и объявление не засчитано ранее (навсегда, не за день);
         *     · listing.compared — минимум два разных listingId;
         *     · listing.favorited — не чаще одного раза в сутки;
         *     · задачи привязаны к categoryId, никогда к конкретному объявлению или продавцу.
         *
         *     ПОЛЕ source ОБЯЗАТЕЛЬНО. Значение gamified означает, что действие вызвано задачей. Бэк обязан пробросить флаг в аналитику Авито, и такие события ИСКЛЮЧАЮТСЯ из статистики продавца и из ранжирования — иначе геймификация создаёт фальшивый спрос.
         *
         *     События seller.contacted, ad.published, deal.completed, review.left начисляют XP, но НИКОГДА не выдаются как задачи: просить об этом значит спамить продавцов.
         *
         *     В MVP события шлёт фронт из встроенной ленты. В проде — шина событий Авито. Схема одна и та же.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description UUID с клиента. Повтор с тем же ключом возвращает прежний результат, а не ошибку. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        events: components["schemas"]["ActivityEvent"][];
                    };
                };
            };
            responses: {
                /** @description Пересчитанное состояние */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ActivityResult"];
                        };
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Серия дней
         * @description День засчитывается при выполнении хотя бы одной задачи ИЛИ двух действий ухода. Пересчёт в 04:00 по timezone. При пропуске автоматически списывается заморозка, если есть. Поле best никогда не уменьшается.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Состояние стрика */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Streak"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streak/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Вехи хранилища стрика */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список вех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Milestone"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Косметика — полученная и закрытая
         * @description Косметика НЕ влияет на экономику: ни на XP, ни на показатели, ни на настроение. Только внешность. Бэк хранит assetKey, картинку рисует фронт — добавление скина не требует деплоя бэка.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список предметов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Cosmetic"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/{cosmeticId}/equip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Надеть предмет
         * @description Один предмет на слот: надевание второго вытесняет первый.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cosmeticId: components["parameters"]["CosmeticId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Питомец и инвентарь обновлены */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: {
                                pet?: components["schemas"]["Pet"];
                                cosmetics?: components["schemas"]["Cosmetic"][];
                            };
                        };
                    };
                };
                /** @description COSMETIC_NOT_OWNED */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/{cosmeticId}/unequip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Снять предмет */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cosmeticId: components["parameters"]["CosmeticId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Обновлено */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Награды
         * @description promoCode ОТСУТСТВУЕТ, пока status не claimed или used. До получения фронт рисует маску. Иначе коды собираются скрейпингом.
         *
         *     conditionLabel и etaDays считает сервер: фронт не склеивает фразы из чисел, иначе смена экономики потребует правки клиента.
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["RewardStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список наград */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Reward"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ближайшая награда по прогрессу */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Награда */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Reward"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/{rewardId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Забрать награду
         * @description Идемпотентно. Повтор с ТЕМ ЖЕ Idempotency-Key возвращает 200 и тот же промокод.
         *
         *     При другом ключе по уже полученной награде возвращается 409 REWARD_ALREADY_CLAIMED, но в data лежит ТОТ ЖЕ промокод — фронт открывает шит с кодом, а не показывает ошибку.
         *
         *     Если tier=cosmetic, сервер сразу выдаёт предмет и шлёт по сокету cosmetic.granted.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен: ретрай при плохой сети не должен выдать второй промокод. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                };
                path: {
                    rewardId: components["parameters"]["RewardId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["RewardOk"];
                /** @description REWARD_NOT_ELIGIBLE — условие не выполнено */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description REWARD_ALREADY_CLAIMED. В data — та же награда с промокодом */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"] & {
                            data?: components["schemas"]["Reward"];
                        };
                    };
                };
                /** @description REWARD_EXPIRED */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/{rewardId}/redeem-click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Лог перехода «Применить на Авито»
         * @description Метрика конверсии. Реальное погашение происходит на стороне Авито, статус переходит в used отдельным серверным событием.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    rewardId: components["parameters"]["RewardId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Записано */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Сводка дня
         * @description Решение о показе принимает СЕРВЕР через поле shouldShow. Клиент не вычисляет «наступил ли вечер»: перевод часов на устройстве сломал бы логику.
         */
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Сводка */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["DailySummary"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary/daily/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отметить сводку просмотренной */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        date: string;
                    };
                };
            };
            responses: {
                /** @description Записано */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Лидерборд
         * @description Поле me приходит ОТДЕЛЬНО от items, независимо от страницы: иначе свою строку пришлось бы искать по всем страницам. Ранжирование по XP за 7 дней, тай-брейк — длина стрика. Отдаются только публичные поля.
         */
        get: {
            parameters: {
                query: {
                    scope: "league" | "friends" | "top";
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Страница лидерборда */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["LeaderboardPage"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль: стрик, статистика, счётчики */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Профиль */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Profile"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/advance-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Прокрутить сутки
         * @description Только при DEMO_MODE=true, иначе 404. Нужен, чтобы показать жюри вехи на 100 и 500 дней за пять минут защиты: прокручивает decay, стрик, ротацию задач и сборку сводки.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default 1 */
                        days?: number;
                    };
                };
            };
            responses: {
                200: components["responses"]["PetOk"];
                /** @description Демо-режим выключен */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /** @description Полезная нагрузка. null при ошибке */
            data?: unknown;
            meta: components["schemas"]["Meta"];
        };
        Meta: {
            /**
             * @description ВСЕГДА число, дублирует HTTP-статус
             * @example 200
             */
            code: number;
            /** @description Текст для пользователя, на русском */
            message: string;
            error?: components["schemas"]["ErrorCode"];
            /**
             * Format: uuid
             * @description Эхо заголовка X-Request-Id. По нему бэк находит лог по скриншоту бага
             */
            requestId?: string;
            /** @description Только при 429 */
            retryAfterSec?: number;
        };
        ErrorEnvelope: {
            data?: null;
            meta: components["schemas"]["Meta"];
        };
        /**
         * @description Машинный код. Фронт ветвится ТОЛЬКО по нему: message перепишут при вычитке текстов, и клиент молча сломается.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHORIZED" | "TOKEN_EXPIRED" | "NOT_FOUND" | "PET_ALREADY_EXISTS" | "PET_IS_SLEEPING" | "ACTION_LIMIT_REACHED" | "ACTION_RATE_LIMITED" | "EVENT_REJECTED" | "REWARD_NOT_ELIGIBLE" | "REWARD_ALREADY_CLAIMED" | "REWARD_EXPIRED" | "COSMETIC_NOT_OWNED" | "INTERNAL_ERROR";
        Tokens: {
            accessToken: string;
            refreshToken: string;
            /** @example 900 */
            expiresIn?: number;
        };
        AuthResult: components["schemas"]["Tokens"] & {
            user?: components["schemas"]["Me"];
        };
        Me: {
            id: string;
            nickname: string;
            /** Format: uri */
            avatarUrl?: string;
            /** @example Europe/Moscow */
            timezone: string;
            /**
             * @description Определяет выдачу задач. Задачи продавца бессмысленны без активных объявлений
             * @enum {string}
             */
            segment: "buyer" | "seller" | "both";
            /** @description Флаг на сервере, а не в localStorage: иначе онбординг повторится на другом устройстве */
            onboardingCompleted: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @enum {string} */
        PresetId: "green" | "blue" | "purple";
        PetPreset: {
            id?: components["schemas"]["PresetId"];
            /** @example Ави */
            name?: string;
            /** @example спокойный */
            trait?: string;
            /** @description Четыре цвета логотипа Авито в ролях: тело, большое ухо, малое ухо, лапа */
            colors?: {
                body?: string;
                earL?: string;
                earS?: string;
                paw?: string;
            };
        };
        /** @enum {string} */
        StatKey: "hunger" | "joy" | "clean" | "energy";
        /** @description Целые 0..100. Потолок жёсткий: 82 + 30 = 100, остаток сгорает */
        Stats: {
            hunger: number;
            joy: number;
            clean: number;
            energy: number;
        };
        /** @enum {string} */
        PetActionKind: "feed" | "play" | "wash" | "sleep" | "wake";
        /**
         * @description Производная от МИНИМАЛЬНОГО показателя. Клиент её не вычисляет
         * @enum {string}
         */
        PetMood: "radiant" | "happy" | "neutral" | "sad" | "sick" | "sleeping";
        ActionState: {
            /** @description Сколько раз ещё можно сегодня */
            remaining: number;
            /** Format: date-time */
            cooldownUntil?: string;
            /** @description Суточный потолок ухода исчерпан */
            xpCapped: boolean;
        };
        Pet: {
            id: string;
            presetId: components["schemas"]["PresetId"];
            name: string;
            level: number;
            /** @description XP внутри текущего уровня */
            xp: number;
            /** @description round10(100 * 1.25^(level-1)) */
            xpToNext: number;
            totalXp: number;
            /** @enum {integer} */
            stage: 1 | 2 | 3 | 4;
            /** @example Искатель */
            stageLabel?: string;
            stats: components["schemas"]["Stats"];
            mood: components["schemas"]["PetMood"];
            /** @example 1 */
            moodMultiplier: number;
            /** @example 1.2 */
            streakMultiplier?: number;
            /** Format: date-time */
            sleepUntil?: string;
            actions: {
                [key: string]: components["schemas"]["ActionState"];
            };
            /** @description id надетой косметики */
            equipped?: string[];
            nextStage?: {
                stage?: number;
                label?: string;
                atLevel?: number;
            };
            /**
             * Format: date-time
             * @description Момент, на который посчитан decay. Точка отсчёта для следующего пересчёта
             */
            updatedAt: string;
        };
        ActionResult: {
            pet: components["schemas"]["Pet"];
            /** @description Уже с множителями и округлением вниз */
            xpGained: number;
            /** @description Показатель был 100 ДО действия. XP не начислен, анимацию всё равно играем */
            statCapped: boolean;
            /** @description Сколько XP ухода начислено за сутки */
            careXpToday?: number;
            careXpCapReached?: boolean;
            leveledUp: boolean;
            unlockedRewardIds?: string[];
        };
        /**
         * @description care — внутри игры; setup — нулевой след у других людей (сохранить поиск, обновить фото своего объявления); explore — слабый след (просмотры, сравнение, избранное); weekly — недельная
         * @enum {string}
         */
        TaskClass: "care" | "setup" | "explore" | "weekly";
        Task: {
            id: string;
            class: components["schemas"]["TaskClass"];
            /** @example Посмотри 3 объявления */
            title: string;
            /** @example в разделе «Электроника» */
            subtitle?: string;
            /** @description Ключ иконки, фронт рисует SVG сам */
            icon: string;
            xpReward: number;
            progress: {
                current: number;
                target: number;
            };
            /** @enum {string} */
            status: "active" | "completed" | "expired";
            /** Format: uri */
            deepLink?: string;
            requiresEvent?: components["schemas"]["ActivityType"][];
            /** Format: date-time */
            expiresAt: string;
        };
        TasksToday: {
            items?: components["schemas"]["Task"][];
            /**
             * Format: date-time
             * @description 04:00 по timezone аккаунта
             */
            resetsAt?: string;
        };
        /**
         * @description Первые девять могут быть задачами. Последние четыре — только признания: дают XP, но никогда не выдаются как задача, иначе продавцы получат спам
         * @enum {string}
         */
        ActivityType: "listing.viewed" | "listing.compared" | "listing.favorited" | "search.saved" | "profile.updated" | "ad.photo_updated" | "ad.delivery_enabled" | "autoteka.report_viewed" | "delivery.section_opened" | "seller.contacted" | "ad.published" | "deal.completed" | "review.left";
        ActivityEvent: {
            /**
             * Format: uuid
             * @description Для дедупликации
             */
            eventId: string;
            type: components["schemas"]["ActivityType"];
            /** Format: date-time */
            occurredAt: string;
            /**
             * @description gamified означает «вызвано задачей». Бэк обязан пробросить флаг в аналитику: такие события исключаются из статистики продавца и из ранжирования
             * @enum {string}
             */
            source: "gamified" | "organic";
            payload?: {
                listingId?: string;
                listingIds?: string[];
                categoryId?: string;
                adId?: string;
                /** @description Для listing.viewed зачёт от 8000 */
                dwellMs?: number;
                queryHash?: string;
                fields?: string[];
            };
        };
        ActivityResult: {
            accepted?: string[];
            rejected?: {
                eventId?: string;
                /** @enum {string} */
                reason?: "DWELL_TOO_SHORT" | "ALREADY_COUNTED" | "NO_MATCHING_TASK" | "DAILY_LIMIT" | "DUPLICATE";
            }[];
            tasks?: components["schemas"]["Task"][];
            xpGained?: number;
            pet?: components["schemas"]["Pet"];
            leveledUp?: boolean;
            unlockedRewardIds?: string[];
        };
        Streak: {
            current: number;
            /** @description Никогда не уменьшается */
            best: number;
            freezes: number;
            todayCounted: boolean;
            /**
             * @description 1–6 дн ×1.0 · 7–13 ×1.1 · 14–29 ×1.2 · 30–99 ×1.3 · 100–499 ×1.4 · 500+ ×1.5
             * @example 1.2
             */
            multiplier: number;
            /** @description Заморозка списана автоматически — сказать честно в сводке */
            frozenUsed?: boolean;
            broken?: boolean;
            nextMilestone?: {
                days?: number;
                title?: string;
                daysLeft?: number;
                rewardId?: string;
            };
        };
        Milestone: {
            /** @example 100 */
            days?: number;
            /** @example Сотня */
            title?: string;
            /** @enum {string} */
            status?: "passed" | "current" | "locked";
            rewardId?: string;
        };
        /** @enum {string} */
        CosmeticSlot: "skin" | "accessory" | "background" | "frame";
        /** @enum {string} */
        Rarity: "common" | "rare" | "legendary";
        Cosmetic: {
            id: string;
            slot: components["schemas"]["CosmeticSlot"];
            /** @example Шарф исследователя */
            name: string;
            rarity: components["schemas"]["Rarity"];
            /**
             * @description Ключ, по которому фронт рисует SVG. Бэк картинок не хранит
             * @example scarf_explorer
             */
            assetKey: string;
            owned: boolean;
            equipped: boolean;
            source?: {
                /** @enum {string} */
                type?: "level" | "streak" | "reward";
                /** @example Веха 7 дней */
                label?: string;
            };
            /** @example Откроется на 10 уровне */
            lockedHint?: string;
            /** Format: date-time */
            obtainedAt?: string;
        };
        /**
         * @description cosmetic — себестоимость 0 · soft — бонусы кошелька, мелкие скидки · premium — платные услуги Авито, только с 10 уровня и вехи 100
         * @enum {string}
         */
        RewardTier: "cosmetic" | "soft" | "premium";
        /** @enum {string} */
        RewardStatus: "locked" | "available" | "claimed" | "used" | "expired";
        Reward: {
            id: string;
            tier: components["schemas"]["RewardTier"];
            /** @example Скидка 20% на Авито Доставку */
            title: string;
            description?: string;
            /**
             * @description ГОТОВЫЙ текст с сервера. Фронт не склеивает фразы из чисел
             * @example Достигни 10 уровня
             */
            conditionLabel: string;
            progress: {
                current: number;
                target: number;
                /** @enum {string} */
                unit: "level" | "day" | "task";
            };
            /** @description Оценка сервера по темпу пользователя */
            etaDays?: number;
            status: components["schemas"]["RewardStatus"];
            /** @description Если tier=cosmetic */
            cosmeticId?: string;
            /**
             * @description ТОЛЬКО при status claimed или used. В остальных случаях поле отсутствует
             * @example AVI-7K3M-92XQ
             */
            promoCode?: string;
            /** Format: uri */
            redeemUrl?: string;
            /** Format: date-time */
            claimedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        DailySummary: {
            /** Format: date */
            date?: string;
            /** @description Решает сервер, не клиент */
            shouldShow?: boolean;
            xpTotal?: number;
            multiplier?: number;
            breakdown?: {
                key?: string;
                label?: string;
                count?: number;
                xp?: number;
            }[];
            streak?: components["schemas"]["Streak"];
            pet?: {
                levelBefore?: number;
                levelAfter?: number;
                moodBefore?: components["schemas"]["PetMood"];
                moodAfter?: components["schemas"]["PetMood"];
                statsAfter?: components["schemas"]["Stats"];
            };
            tomorrow?: {
                tasks?: components["schemas"]["Task"][];
                streakWillBe?: number;
                multiplierWillBe?: number;
                nextReward?: components["schemas"]["Reward"];
            };
            /** @description Персональная фраза от питомца. Генерируется на бэке: ключи LLM не должны попасть в браузер */
            aiNote?: string;
        };
        LeaderboardEntry: {
            rank?: number;
            userId?: string;
            nickname?: string;
            presetId?: components["schemas"]["PresetId"];
            level?: number;
            weeklyXp?: number;
            streak?: number;
            isMe?: boolean;
        };
        LeaderboardPage: {
            /** @enum {string} */
            scope?: "league" | "friends" | "top";
            league?: {
                id?: string;
                name?: string;
                /** Format: date-time */
                endsAt?: string;
                promoteCount?: number;
                relegateCount?: number;
            };
            me?: components["schemas"]["LeaderboardEntry"];
            items?: components["schemas"]["LeaderboardEntry"][];
            nextCursor?: string;
        };
        Profile: {
            user?: components["schemas"]["Me"];
            pet?: components["schemas"]["Pet"];
            streak?: components["schemas"]["Streak"];
            stats?: {
                daysInGame?: number;
                careActions?: number;
                tasksCompleted?: number;
                rewardsClaimed?: number;
                avgXpPerDay?: number;
            };
            /** @description Хитмап за 30 дней */
            activity?: {
                /** Format: date */
                date?: string;
                value?: number;
            }[];
        };
        Config: {
            stats?: {
                [key: string]: {
                    label?: string;
                    decayPerHour?: number;
                    color?: string;
                };
            };
            actions?: {
                [key: string]: {
                    label?: string;
                    stat?: components["schemas"]["StatKey"];
                    effect?: number;
                    xp?: number;
                    dailyLimit?: number;
                };
            };
            /** @example 40 */
            dailyCareXpCap?: number;
            moods?: {
                id?: components["schemas"]["PetMood"];
                label?: string;
                minStat?: number;
                multiplier?: number;
            }[];
            levelCurve?: {
                /** @example 100 */
                base?: number;
                /** @example 1.25 */
                factor?: number;
                /** @example 10 */
                roundTo?: number;
                /** @example 25 */
                maxLevel?: number;
            };
            streakTiers?: {
                from?: number;
                multiplier?: number;
            }[];
            milestones?: components["schemas"]["Milestone"][];
        };
    };
    responses: {
        /** @description Состояние питомца */
        PetOk: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Pet"];
                };
            };
        };
        /** @description Награда */
        RewardOk: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Reward"];
                };
            };
        };
        /** @description UNAUTHORIZED или TOKEN_EXPIRED. На TOKEN_EXPIRED фронт делает refresh и повторяет запрос один раз */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description VALIDATION_ERROR */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description NOT_FOUND */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description ACTION_RATE_LIMITED. В meta.retryAfterSec — через сколько можно повторить */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description UUID с клиента. Повтор с тем же ключом возвращает прежний результат, а не ошибку. */
        IdempotencyKey: string;
        /** @description Обязателен: ретрай при плохой сети не должен выдать второй промокод. */
        IdempotencyKeyRequired: string;
        TaskId: string;
        RewardId: string;
        CosmeticId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
